server:
  port: 13000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /dldsj/

spring:
  application:
    name: ${application-info.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dn07:3306/dldsj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: admin
    password: Admin1234.
    hikari:
      auto-commit: true
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 3000
      connection-test-query: select 1
      connection-timeout: 3000
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    static-path-pattern: static/**
  resources:
    static-locations:
      - file://${settings.picPath}
      - classpath:/static

#logging:
#  level:
#    edu.zju.gis.dldsj.dao: DEBUG

es-info:
  version: 5.5.1
  cluster-name: es
  host-name-list: nn01,nn02,dn01,dn02,dn03,dn04,dn05,dn06,dn07
  host-name: nn01
  host-name2: nn02
  transport-port: 9300
  http-port: 9200

#logging:
#  level:
#    edu.zju.gis.dldsj.dao: DEBUG

settings:
  parallelFilePath: /opt/dldsj/upload
  jarPath: ${settings.parallelFilePath}/jar
  xmlPath: ${settings.parallelFilePath}/xml
  templatePath: ${settings.parallelFilePath}/template
  picPath: ${settings.parallelFilePath}/pic
  metaPath: /opt/dldsj/metadata
  nameNode: nn01
  username: root
  password: 1234qwer@2019
  javaHome: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/
  hadoopHome: /home/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179
  sparkHome: /home/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179
  esHost: dn01
  esPort: 9200
  esName: es
  esIndex: dls
  jobMonitor: http://nn02:8088/ws/v1/cluster/apps
  monitorInterval: 2000
  jobFailInterval: 20000
  jobResultPath: /gee
  initTaskPoolSize: 3
  maxTaskPoolSize: 20
  keepAliveSeconds: 60
  dagsFolder: /root/airflow/dags
  frontEndRegionList:
    - http://nn01:8081
    - http://nn02:8081
    - http://192.168.240.25:8081
    - http://192.168.240.28:8081
    - http://159.226.110.96:8081
    - http://localhost:8082
    - http://192.168.240.38:8200
    - http://159.226.110.101:8200
  sessionMaxAge: 36000
  rasterToolTempDir: 192.168.240.25
  topic3ToolTempDir: /home/share/
  userSpaceRootPath: /czd/dldsj/userSpace/
  exportToolJarClass: edu.zju.gis.dldsj.model.loader.DataExtractor
  exportToolJarPath: /home/dldsj/test/test.jar
  importToolJarClass: edu.zju.gis.dldsj.model.loader.ESDataLoader
  importToolJarPath: /home/dldsj/test/loader.jar
  calculateDataNameSpace: /calculateData/
  selfDataNameSpace: /selfData/
  systemPublicAccount: SYSTEM_PUBLIC
  downloadTempDirectory: /home/dldsj/downloadTempDirectory/
  airFlowHome: /root/airflow
  airFlowDagsPath: ${settings.airFlowHome}/dags