server:
  port: 13000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /dldsj/


spring:
  application:
    name: ${application-info.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dldsj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: czdsaw123
    hikari:
      auto-commit: true
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 3000
      connection-test-query: select 1
      connection-timeout: 3000
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    static-path-pattern: static/**
  resources:
    static-locations:
      - file://${settings.picPath}
      - classpath:/static

#logging:
#  level:
#    edu.zju.gis.dldsj.dao: DEBUG

es-info:
  version: 5.5.1
  cluster-name: elasticsearch
  host-name-list: ubt1,ubt2,ubt3
  host-name: 192.168.1.5
  host-name2: 192.168.1.7
  transport-port: 9300
  http-port: 9200

#logging:
#  level:
#    edu.zju.gis.dldsj.dao: DEBUG
settings:
  parallelFilePath: /opt/dldsj/upload
  jarPath: ${settings.parallelFilePath}/jar
  xmlPath: ${settings.parallelFilePath}/xml
  templatePath: ${settings.parallelFilePath}/template
  picPath: ${settings.parallelFilePath}/pic
  metaPath: /opt/dldsj/metadata
  nameNode: 192.168.1.5
  username: root
  password: ubt123
  javaHome: /opt/tool/jdk8
  hadoopHome: /opt/tool/hadoop
  sparkHome: /opt/tool/spark
  esHost: ubt1
  esPort: 9300
  esName: elasticsearch
  esIndex: dls
  jobMonitor: http://${settings.nameNode}:8088/ws/v1/cluster/apps
  monitorInterval: 2000
  jobFailInterval: 20000
  jobResultPath: /gee
  initTaskPoolSize: 3
  maxTaskPoolSize: 20
  keepAliveSeconds: 60
  dagsFolder: /home/ubt/airflow/dags
  frontEndRegionList:
    - http://localhost:8082
    - http://192.168.1.5:8082
    - http://ubt1:8082
  sessionMaxAge: 36000
  rasterToolTempDir: /output/
  topic3ToolTempDir: /home/share/
  userSpaceRootPath: /czd/dldsj/userSpace/
  calculateDataNameSpace: /calculateData/
  selfDataNameSpace: /selfData/
  systemPublicAccount: SYSTEM_PUBLIC
  airFlowHome: /home/ubt/airflow
  airFlowDagsPath: ${settings.airFlowHome}/dags