application-info:
  name: "eduPlatform"
  version: "0.1.0_alpha"
  authority: "浙江大学GIS重点实验室"
  release: "2020-07-27"

Spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml,edu.zju.gis.dldsj.server.mapper/*.xml
