server:
  port: 13000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /summer/


spring:
  application:
    name: ${application-info.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.79.231.81:3306/eduPlatform?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: group4
    password: zjugis_group4
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    static-path-pattern: static/**
  resources:
    static-locations:
      - file://${settings.picPath}
      - classpath:/static

#logging:
#  level:
#    edu.zju.gis.dldsj.dao: DEBUG

settings:
  frontEndRegionList:
    - http://localhost:8082
    - http://10.79.231.81:8082
    - http://td1:8082
  sessionMaxAge: 36000
